<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharpMath.Ios.Tests</RootNamespace>
    <AssemblyName>CSharpMath.Ios.Tests</AssemblyName>
    <SupportedOSPlatformVersion>13.5</SupportedOSPlatformVersion>
  </PropertyGroup>
  <PropertyGroup Condition="!$([System.String]::IsNullOrEmpty($(CI))) And $(CI)">
    <DefineConstants>$(DefineConstants);CI</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.devices" Version="2.5.25" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\CSharpMath.Rendering.Tests\TestRenderingMathData.cs">
      <Link>TestRenderingMathData.cs</Link>
    </Compile>
    <Compile Include="..\CSharpMath.Rendering.Tests\TestRenderingSharedData.cs">
      <Link>TestRenderingSharedData.cs</Link>
    </Compile>
    <EmbeddedResource Include="..\CSharpMath.Rendering.Tests\MathDisplay\*" Exclude="..\CSharpMath.Rendering.Tests\MathDisplay\*.*.*" Link="MathDisplay\%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\CSharpMath.Rendering.Tests\MathInline\*" Exclude="..\CSharpMath.Rendering.Tests\MathInline\*.*.*" Link="MathInline\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CSharpMath\CSharpMath.csproj" />
    <ProjectReference Include="..\CSharpMath.Ios\CSharpMath.Ios.csproj" />
  </ItemGroup>
</Project>
