<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="_Helpers\Resources\latinmodern-math.json" />
    <ProjectReference Include="..\CSharpMath\CSharpMath.csproj" />
    <ProjectReference Include="..\CSharpMath.TestUtils\CSharpMath.CoreTestUtils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="GitHubActionsTestLogger" Version="3.0.1" />
    <PackageReference Update="xunit" Version="2.9.3" />
    <PackageReference Update="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="Xunit.SkippableFact" Version="1.5.23" />
  </ItemGroup>
</Project>