<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="_Helpers\Resources\latinmodern-math.json" />
    <ProjectReference Include="..\CSharpMath\CSharpMath.csproj" />
    <ProjectReference Include="..\CSharpMath.Tests.FrontEnd\CSharpMath.Tests.FrontEnd.csproj" />
  </ItemGroup>
</Project>