<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>The Uno/WinUI front end for CSharpMath.</Description>
    <PackageTags>$(PackageTags) uno</PackageTags>
	<DefineConstants>$(DefineConstants) Uno</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
	<Compile Include="..\CSharpMath.Xaml\**\*.cs" Link="%(RecursiveDir)%(Filename)%(Extension)" />
	<ProjectReference Include="..\CSharpMath.SkiaSharp\CSharpMath.SkiaSharp.csproj" />
	<PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="3.119.1" />
  </ItemGroup>
</Project>