<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>CSharpMath.TestUtils</AssemblyName>
    <RootNamespace>CSharpMath.TestUtils</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\CSharpMath.CoreTests\_Helpers\Resources\latinmodern-math.json" Link="Resources\latinmodern-math.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharpMath\CSharpMath.csproj" />
    <ProjectReference Include="..\CSharpMath.Editor\CSharpMath.Editor.csproj" />
  </ItemGroup>
</Project>
