<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CSharpMath.Avalonia" Version="0.5.0-alpha4" />
    <PackageReference Include="CSharpMath.Forms" Version="0.5.1" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <Compile Include="../CSharpMath.Xaml.Tests/XamarinFormsCrc64.cs" Link="XamarinFormsCrc64.cs" />
    <Compile Include="../CSharpMath.Xaml.Tests/XamarinFormsMockPlatformServices.cs" Link="XamarinFormsMockPlatformServices.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="GitHubActionsTestLogger" Version="3.0.1" />
    <PackageReference Update="xunit" Version="2.9.3" />
    <PackageReference Update="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="Xunit.SkippableFact" Version="1.5.23" />
  </ItemGroup>
</Project>