<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\latinmodern-math.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharpMath\CSharpMath.csproj" />
    <ProjectReference Include="..\CSharpMath.Editor\CSharpMath.Editor.csproj" />
  </ItemGroup>
</Project>
