name: Build

on: [push, pull_request]
jobs:
  Everything:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: .NET Workload restore
      run: dotnet workload restore
    - name: Restore NuGet Packages
      run: dotnet restore CSharpMath.sln
    - name: Build Everything
      run: dotnet build CSharpMath.sln /p:Configuration=Release
