name: Build

on: [push, pull_request]
jobs:
  Everything:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v2
    - name: Restore NuGet Packages
      run: nuget restore CSharpMath.sln
    - name: Build Everything
      run: msbuild CSharpMath.sln /p:Configuration=Release
