name: Build and Test

on: [push, pull_request]
jobs:
  Everything:
    if: (github.event_name == 'pull_request') == github.event.pull_request.head.repo.fork
    strategy:
      fail-fast: false # Don't cancel other os builds if one fails
      matrix:
        # Check included Xcode versions for GitHub Actions: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [windows-latest, ubuntu-latest, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      if: startsWith(matrix.os, 'macos')
      with:
        # Check required Xcode version for latest "dotnet workload restore": https://github.com/dotnet/macios/releases
        xcode-version: '26.2' # If this is to be changed, also check macos-version in matrix.os above
    - uses: actions/setup-dotnet@main
      if: matrix.os != 'ubuntu-latest'
      with:
        dotnet-version: '10.x'
        workloads: maui-ios, maui-maccatalyst, maui-android, wasm-tools
    - uses: actions/setup-dotnet@main
      if: matrix.os == 'ubuntu-latest'
      with:
        dotnet-version: '10.x'
        workloads: maui-android, wasm-tools
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
      # We need to have this configuration because Microsoft.Maui.Resizetizer and Uno.Resizetizer
      # use different native SkiaSharp DLL versions on build time, causing a conflict if both build in parallel for a solution-wide build. 
      # An instance of an exception caused by this can be seen at: https://github.com/verybadcat/CSharpMath/actions/runs/21598419979/job/62237307140

      # C:\Users\runneradmin\.nuget\packages\uno.resizetizer\1.12.1\build\Uno.Resizetizer.android.targets(11,3): error MSB4018:
      # System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
      # ---> System.InvalidOperationException: The version of the native libSkiaSharp library (116.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).

      # This has been reported before: https://github.com/unoplatform/uno/issues/21344 and the resolution was to build MAUI and Uno apps separately.
    - name: Build non-CSharpMath.Uno.Example
      run: dotnet build CSharpMath.slnx -c Not.Uno.Example # Newer macOS workloads may require newer Xcode versions. Update above.
    - name: Build CSharpMath.Uno.Example
      run: dotnet build CSharpMath.Uno.Example
    - name: Run Tests
      run: dotnet test --no-build --solution CSharpMath.slnx
