name: Test

on: [push, pull_request]
jobs:
  CSharpMath.Ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: nuget restore CSharpMath.Ios.Tests
    - run: msbuild CSharpMath.Ios.Tests
